### ISSUE TITLE
Extend UnityEngine.UI.Text class

### ISSUE THREAD

**Issue by tetreum** [minhhh/unity-simplelocalization#1]
Hi! 
Will you also make an extended component of Unity's Text class?
I've checked almost all other open source unity localization systems and all just make a cass that requires Text component to be on the gameobject too which i don't like :(

**Comment by minhhh** [comment]
I'm not sure what you meant by extended component of Unity's Text? In my case, I also create a component which will set the text of the Text component in Awake or Start, based on the key entered in Editor. I think it's the easiest way to apply localized texts to your texts or button.
